spring.application.name=questionary
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-null-for-primitives=true
spring.jackson.deserialization.fail-on-missing-creator-properties=true
spring.jackson.deserialization.fail-on-invalid-subtype=true
